language: R
sudo: false
script:
 - Rscript version_change.R
 - Rscript data_build.R
 - R CMD build .
 - R CMD check *tar.gz
cache: packages
after_success:
 - Rscript drat_deploy.R
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: master
  local-dir: docs
  target-branch: gh-pages
notifications:
  email:
    - ben_barnard@outlook.com
  on_success: always
  on_failure: always
